export const REGISTRO_EXITOSO = 'REGISTRO_EXISTOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO'
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA'